{% set name = "openskill" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: fc23f670cac52e5a12ee1e6b77a79f65809c83e6a6ea67dc0e46ce5a4f4251d9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.10
  run:
    - python >=3.10
    - scipy

test:
  source_files:
    - tests
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
