{% set name = "openskill" %}
{% set version = "5.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: 33156698a326ed9fc4007b1c278e4cb2a7b40a08f3b8cff10c5ec3b39080faab

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -v --no-deps --no-build-isolation
  skip: True  # [py<38]

requirements:
  host:
    - pdm-backend
    - pip
    - python
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: Multiplayer Rating System. No Friction.
  description: A faster and open license asymmetric multi-team, multiplayer rating system comparable to TrueSkill.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/OpenDebates/openskill.py
  doc_url: https://openskill.me/en/stable/

extra:
  recipe-maintainers:
    - thewchan
