{% set name = "openskill" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: 7f28a00961c364387ecf9eeda4e6eea76d9c0cf0890485f90ef4edad4c3865d5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<3.11
  run:
    - python >=3.6,<3.11
    - scipy >=1.8.0,<2.0.0

test:
  source_files:
    - tests
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
