{% set name = "openskill" %}
{% set version = "0.2.0a0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: 0da88d49b101fa69947f79a833d29767feee40df8d7268a412dbd0c779306df6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.6,<3.10
  run:
    - python >=3.6,<3.10
    - scipy >=1.7.1,<2.0.0

test:
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
