{% set name = "openskill" %}
{% set version = "0.2.0b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openskill-{{ version }}.tar.gz
  sha256: b792b29adac8781f8fde9566da35b8c974681ae8c4c011abd7f361e519ee293a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<3.11
  run:
    - python >=3.6,<3.11
    - scipy >=1.7.1,<2.0.0

test:
  source_files:
    - tests
  imports:
    - openskill
    - openskill.models
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/OpenDebates/openskill.py
  summary: License-free implementation of Weng-Lin Bayesian ranking
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
